### ISSUE TITLE
setItemMargin breaks scrolling

### ISSUE THREAD

**Issue by snodnipper** [maurycyw/StaggeredGridView#1]
Using setItemMargin on a multi column gridview prevents up scrolling (towards the first child).

To repeat:

> staggered:numColumns="2"
> sgv.setItemMargin(10);

Specifying one column or removing the margin call restores normal behaviour.

**Comment by maurycyw** [comment]
Thank you just verified this. Will work on a fix asap.  Also anyone can feel free to contribute a fix :).
