### ISSUE TITLE
Support space between items

### ISSUE THREAD

**Issue by spacecowboy** [maurycyw/StaggeredGridView#13]
Would be nice if the view had an attribute specifying the spacing between items (vertical and horizontal) like the regular GridView.

Using a workaround right now with padding inside my item-layouts.

**Comment by shanerelay** [comment]
See the "setItemMargin" function in the source code:

https://github.com/maurycyw/StaggeredGridView/blob/master/src/com/origamilabs/library/views/StaggeredGridView.java
