### ISSUE TITLE
The Listener Problem

### ISSUE THREAD

**Issue by waiwu9292** [maurycyw/StaggeredGridView#24]
I cannot set any listener in StaggeredGridView item.
like this : 

gridView.setOnItemClickListener(new OnItemClickListener() {
            @Override
            public void onItemClick(AdapterView<?> parent, View view,
                    int position, long id) {

```
        }
    });
```

Please help me about that.

**Comment by justinmc** [comment]
Close, I think it should be like this:

``` Java
gridView.setOnItemClickListener(new StaggeredGridView.OnItemClickListener() {
    @Override
    public void onItemClick(StaggeredGridView parent, View view, int position, long id) {
        // TODO
    }
});
```
