### ISSUE TITLE
Problem loading images when scrolling slow

### ISSUE THREAD

**Issue by gafrancischini** [maurycyw/StaggeredGridView#27]
When scrolling the gridview slowly some images doesn't load correctly.

When scrolling fast and then stops scrolling everything seems fine.

**Comment by briangriffey** [comment]
Without a specific example I can not reproduce.

**Comment by briangriffey** [comment]
@gafrancischini My guess is that your ImageViews haven't gotten a size yet because the the image hasn't loaded yet.  I'm going to close this issue unless you can give me something with specific code to reproduce the issue.
