### ISSUE TITLE
Scrolling Back up does not work

### ISSUE THREAD

**Issue by utopiadevelopers** [maurycyw/StaggeredGridView#29]
I am able to scroll down but when I try to scroll up I am unable to.It just seems that the list ends there.
I am facing this problem in android 4.2.2 both on emulator and actual device.

**Comment by briangriffey** [comment]
I can't replicate this.

**Comment by Queatz** [comment]
This happens sometimes.  It seems to be when you scroll fast down, not giving enough time for the items to load completely; it's rather annoying, but you can get past the "block" by swiping up quickly.

**Comment by briangriffey** [comment]
@Queatz I believe this has more to do with the end implementation of image loading rather than the actual scroll view itself.

**Comment by Queatz** [comment]
@briangriffey In my case I immediately set the size of the cell based on the images' aspects before loading the image, so the cell size remains constant.
