### ISSUE TITLE
bug---     in.createIntArray(topOffsets);

### ISSUE THREAD

**Issue by cding24** [maurycyw/StaggeredGridView#36]
private SavedState(Parcel in) {
            super(in);
            firstId = in.readLong();
            position = in.readInt();
            in.createIntArray(topOffsets);
            in.readTypedList(mapping, ColMap.CREATOR);

```
    }
```

**Comment by aarya123** [comment]
Change that line to the following for now

```
in.readIntArray(topOffsets);
```

**Comment by maurycyw** [comment]
A fix is supposed to be merged
