### ISSUE TITLE
Include LICENSE

### ISSUE THREAD

**Issue by vinc3m1** [maurycyw/StaggeredGridView#41]
Some of the files have Apache License Headers, but a full license should probably be included in the repo

**Comment by BenoitDuffez** [comment]
I agree. I would like to use it on my apps but I don't know what to put in the credits/license section.

**Comment by vinc3m1** [comment]
I think it's safe to assume Apache 2 for now, If you want to open a PR to add the Apache License file I will accept it

**Comment by briangriffey** [comment]
@vinc3m1 @BenoitDuffez I just pushed a license file to master.

**Comment by vinc3m1** [comment]
thanks @briangriffey!

**Comment by BenoitDuffez** [comment]
Great!
