### ISSUE TITLE
NullPointerException in onTouchEvent

### ISSUE THREAD

**Issue by mingfai** [maurycyw/StaggeredGridView#48]
No idea how to repeat it. It occasionally happen. 

```
java.lang.NullPointerException
    at com.origamilabs.library.views.StaggeredGridView.onTouchEvent(SourceFile:545)
    at android.view.View.dispatchTouchEvent(View.java:7143)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2238)
```

The line number may be slightly different at my local version. It refers to the "if" line and the NPE is caused by a null mAdapter in "mAdapter.isEnabled(motionPosition)". A patch is as follows:

```

    public boolean onTouchEvent(MotionEvent ev) {
                /**
                 * PATCHED: mAdapter may cause NPE
                 */
                if (!mDataChanged && mAdapter!=null && mAdapter.isEnabled(motionPosition)) { /** line 545 */
                    // TODO : handle
                    mTouchMode = TOUCH_MODE_TAP;
                } else {
                    mTouchMode = TOUCH_MODE_REST;
                }

```

**Comment by mingfai** [comment]
well... mAdapter refers to the adapter the adapter I set to the StaggeredGridView. So it is probably a bug in my code. My code does switch adapters in runtime. Should I close this issue or wait for StaggeredGridView to add a NPE protection?

**Comment by kitek** [comment]
+1

**Comment by briangriffey** [comment]
This should be protected in the grid view. I can see where there will be some NPEs when the adapter is null onTouch.
