### ISSUE TITLE
Scrolling issues

### ISSUE THREAD

**Issue by radzio** [maurycyw/StaggeredGridView#5]
Scrolling down is working great however when I want to scroll up it does not work. I was testing it on Nexus 7, Android 4.2.1

**Comment by plackemacher** [comment]
Same issue on Nexus 4, Android 4.2.1

**Comment by maurycyw** [comment]
Are you sure you have the latest version of StaggeredGridView.. I just tested the StaggeredGridViewDemo on my Nexus 7 and works fine.

**Comment by plackemacher** [comment]
Weird.. I tried downloading the source and rebuilding it again and now it doesn't have that issue.

**Comment by maurycyw** [comment]
Great to hear! Let me know if this continues

**Comment by radzio** [comment]
Yeap, everything is ok now ;-)

**Comment by musaulker** [comment]
I have the same problem. I cannot scroll up. I get the latest source of StaggeredGridView and StaggeredGridViewDemo and I cannot scroll up. How can I resolve it?

**Comment by erdosam** [comment]
Just get the latest source, still cannot scroll up

**Comment by aquayee** [comment]
Yes, if use latest source code it can solve the problem. If we simply use git clone, you would not get the latest source code. Just download the zip file, it works fine.

**Comment by erdosam** [comment]
Ah.. It works now.. @aquayee I miss the "download the zipped source instead".. Thx..

**Comment by pawanm** [comment]
Facing the scroll up issue  when I am having large number of elements in staggered grid view with latest source code.  The issue is occurring intermittently when I scroll down in a large data set;
Please check and update;
