### ISSUE TITLE
NullPointerException after back to foreground

### ISSUE THREAD

**Issue by futer24** [maurycyw/StaggeredGridView#52]
09-27 15:47:40.352: W/dalvikvm(21531): threadid=1: thread exiting with uncaught exception (group=0x41581700)
09-27 15:47:40.352: E/AndroidRuntime(21531): FATAL EXCEPTION: main
09-27 15:47:40.352: E/AndroidRuntime(21531): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.staggeredgridviewdemo/com.example.staggeredgridviewdemo.activities.MainActivity}: java.lang.NullPointerException
09-27 15:47:40.352: E/AndroidRuntime(21531):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2211)
09-27 15:47:40.352: E/AndroidRuntime(21531):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2261)
09-27 15:47:40.352: E/AndroidRuntime(21531):    at android.app.ActivityThread.access$600(ActivityThread.java:141)
09-27 15:47:40.352: E/AndroidRuntime(21531):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
09-27 15:47:40.352: E/AndroidRuntime(21531):    at android.os.Handler.dispatchMessage(Handler.java:99)
09-27 15:47:40.352: E/AndroidRuntime(21531):    at android.os.Looper.loop(Looper.java:137)
09-27 15:47:40.352: E/AndroidRuntime(21531):    at android.app.ActivityThread.main(ActivityThread.java:5103)
09-27 15:47:40.352: E/AndroidRuntime(21531):    at java.lang.reflect.Method.invokeNative(Native Method)
09-27 15:47:40.352: E/AndroidRuntime(21531):    at java.lang.reflect.Method.invoke(Method.java:525)
09-27 15:47:40.352: E/AndroidRuntime(21531):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
09-27 15:47:40.352: E/AndroidRuntime(21531):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
09-27 15:47:40.352: E/AndroidRuntime(21531):    at dalvik.system.NativeStart.main(Native Method)
09-27 15:47:40.352: E/AndroidRuntime(21531): Caused by: java.lang.NullPointerException
09-27 15:47:40.352: E/AndroidRuntime(21531):    at android.os.Parcel.readIntArray(Parcel.java:784)
09-27 15:47:40.352: E/AndroidRuntime(21531):    at com.origamilabs.library.views.StaggeredGridView$SavedState.<init>(StaggeredGridView.java:2108)
09-27 15:47:40.352: E/AndroidRuntime(21531):    at com.origamilabs.library.views.StaggeredGridView$SavedState.<init>(StaggeredGridView.java:2104)
09-27 15:47:40.352: E/AndroidRuntime(21531):    at com.origamilabs.library.views.StaggeredGridView$SavedState$1.createFromParcel(StaggeredGridView.java:2132)
09-27 15:47:40.352: E/AndroidRuntime(21531):    at com.origamilabs.library.views.StaggeredGridView$SavedState$1.createFromParcel(StaggeredGridView.java:1)
09-27 15:47:40.352: E/AndroidRuntime(21531):    at android.os.Parcel.readParcelable(Parcel.java:2062)
09-27 15:47:40.352: E/AndroidRuntime(21531):    at android.os.Parcel.readValue(Parcel.java:1971)
09-27 15:47:40.352: E/AndroidRuntime(21531):    at android.os.Parcel.readSparseArrayInternal(Parcel.java:2284)
09-27 15:47:40.352: E/AndroidRuntime(21531):    at android.os.Parcel.readSparseArray(Parcel.java:1693)
09-27 15:47:40.352: E/AndroidRuntime(21531):    at android.os.Parcel.readValue(Parcel.java:2028)
09-27 15:47:40.352: E/AndroidRuntime(21531):    at android.os.Parcel.readMapInternal(Parcel.java:2255)
09-27 15:47:40.352: E/AndroidRuntime(21531):    at android.os.Bundle.unparcel(Bundle.java:223)
09-27 15:47:40.352: E/AndroidRuntime(21531):    at android.os.Bundle.getSparseParcelableArray(Bundle.java:1237)
09-27 15:47:40.352: E/AndroidRuntime(21531):    at com.android.internal.policy.impl.PhoneWindow.restoreHierarchyState(PhoneWindow.java:1644)
09-27 15:47:40.352: E/AndroidRuntime(21531):    at android.app.Activity.onRestoreInstanceState(Activity.java:938)
09-27 15:47:40.352: E/AndroidRuntime(21531):    at android.app.Activity.performRestoreInstanceState(Activity.java:910)
09-27 15:47:40.352: E/AndroidRuntime(21531):    at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1138)
09-27 15:47:40.352: E/AndroidRuntime(21531):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2189)
09-27 15:47:40.352: E/AndroidRuntime(21531):    ... 11 more

Thx!!!!

**Comment by marcosalis** [comment]
The way Parcelable items in StaggeredGridView are created from a Parcel was incorrect.

This has been fixed in ab0dc4835dbc73a889e2306fb6ccd2f10e6e24b4 :

```
    private ColMap(Parcel in) {
        tempMap = in.createIntArray();
        values = new ArrayList<Integer>();
        for (int index = 0; index < tempMap.length; index++) {
            values.add(tempMap[index]);
        }
    }

    private SavedState(Parcel in) {
        super(in);
        firstId = in.readLong();
        position = in.readInt();
        topOffsets = in.createIntArray();
        mapping = in.createTypedArrayList(ColMap.CREATOR);
    }
```

**Comment by briangriffey** [comment]
Thanks @marcosalis

**Comment by futer24** [comment]
thks!
