### ISSUE TITLE
customize selection color 

### ISSUE THREAD

**Issue by accounts01** [maurycyw/StaggeredGridView#54]
hi,

thanks for this awesome view btw. i noticed there was no way of customizing the selection color so i added in this feature. unfortunately, i'm a total git and github noob and since the changes are super simple, i figured i'd post them here and cross my fingers they end up in the main source rather than learn to make pull requests.

i added 2 lines:
a. in res/values/attrs.xml, add this line with the other attribute declarations

`<attr name="selector" format="color|reference" />`

b. in src/.../StaggeredGridView.java, add this line inside the `StaggeredGridView(Context context, AttributeSet attrs, int defStyle)` constructor, alongside the other attribute parsings

`mSelector = a.getDrawable(R.styleable.StaggeredGridView_selector);`

that's it! sorry for being useless with git. hope you enjoy the new feature!

**Comment by briangriffey** [comment]
Hi,

Could you please open a pull request with your suggested changes? 
Thanks

**Comment by accounts01** [comment]
i would've if i knew how and had time to learn :( i'm hoping someone who knows git/github and has got a minute to spare will do it.
cheers!

**Comment by briangriffey** [comment]
Check out this post, it may help: https://help.github.com/articles/using-pull-requests

**Comment by accounts01** [comment]
yeah i'd seen that. thanks though! i'll definitely go through it at some point. unfortunately, i spared all the time i could spare writing my first post. sorry for the inconvenience.
