### ISSUE TITLE
setItemMargin() disables 'scrolling up'

### ISSUE THREAD

**Issue by pcompassion** [maurycyw/StaggeredGridView#6]
It worked great until I started to make it look better with `setitemMargin()`

The view won't scroll up once I set it. and it crashed as well.

I tested on gallaxy s2 with 2.3.3

**Comment by maurycyw** [comment]
Can you please make sure you have the latest version of StaggeredGridView. This was a previously solved issue. I was able to test this on a 2.2.2 & 2.3.x device and it worked fine. Unfortunately I do not have any s2's nearby.

**Comment by pcompassion** [comment]
I just re-cloned your git repo and retried. Same result sadly.

**Comment by yftx** [comment]
I think i find the reason why pcompassion re-clone the repo and it cant scoll up.
I have tried to clone this proj , I clone it and see it was in develop branch .
and I compare the **develop branch** with the **master branch**.
there are something different in _trackMotionScroll()_ funtion in file _StaggeredGridView.java_.
*trackMotionScroll() *controls the view to scroll or not scroll.
I think U will know the reason after u see the difference .

So U checkout the master branch .and then it will be scroll up fine.

**Comment by dancefire** [comment]
Confirmed yftx, just change the branch to 'master' it can scrolling up again.
