### ISSUE TITLE
Android Studio + Gradle compatibility

### ISSUE THREAD

**Issue by Queatz** [maurycyw/StaggeredGridView#66]
Any luck getting this to work with Gradle in Android Studio?  It worked fine without Gradle in Android Studio, however when Exporting to Gradle (from Eclipse) all I've achieved is an unforgivable series of faults.

**Comment by briangriffey** [comment]
I added a build.gradle a few months ago.

**Comment by Queatz** [comment]
Okay I see that now, however when cloning the repo that file doesn't get cloned.  It seems there was some unresolved merge conflict and a Github bug for showing the file, since it's not in the git working tree.

My brother solved it by doing the following:

git cherry-pick 65ce86688c2012aa4f05b5764764d883863fbd46
git checkout --ours libs/android-support-v4.jar
git add .
git commit -am "Merge build.gradle file"
git push
