### ISSUE TITLE
ugly orange selector

### ISSUE THREAD

**Issue by jacekkwiecien** [maurycyw/StaggeredGridView#76]
What's with the orange slection bacground that overlays whole cell weith orange color? Can the color be changed and the selecton pushed into the bacground instead?

**Comment by vinc3m1** [comment]
the selector can be set with `setSelector`, and orange selectors are usually an issue with build target and/or theme.

**Comment by jacekkwiecien** [comment]
Ok then I set the selector like this: listView.setSelector(R.drawable.abc_list_selector_holo_light);

It is a selector I wanted but why it overlays the whole cell?
