### ISSUE TITLE
SwipeRefreshLayout

### ISSUE THREAD

**Issue by rishabhsri20** [maurycyw/StaggeredGridView#96]
Can not implement swipe refresh layout with this view. We can not scroll to the top instead it starts refreshing everytime I try to scroll to top.

**Comment by ghost** [comment]
This happens on any View that you try and wrap a <code>SwipeRefreshLayout</code> around. For it to work, you should consider extending this class and overriding its <code>canChildScrollUp()</code> method and make it return true.

**Comment by sagarmaiyad** [comment]
@insanepaul  can you please give me example of that?

**Comment by ghost** [comment]
Sure.

``` java
public class MySwipeRefreshLayout extends SwipeRefreshLayout {
    ...

    @Override
    public boolean canChildScrollUp() {
        return true;
    }

    ...
}
```

Then use MySwipeRefreshLayout instead of SwipeRefreshLayout in your code.
